# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""
Category 9 (AI features, docs/feature-specs/09-ai-features.md in
plane-selfhost), feature 1 - "Auto-triage assiste par IA". Stores the
current module/assignees/labels suggestion for a newly-created issue,
generated by `plane.utils.issue_triage_suggestion` from the shared
embedding pipeline (`plane.utils.issue_embedding`,
`plane.db.models.issue_embedding.IssueEmbedding` - category 9's own
infrastructure prerequisite, see that module's docstring for why
similarity is plain Python/numpy cosine similarity rather than pgvector).

FIXED SPEC FABRICATION - MODULE CARDINALITY: the spec's own data-model
section (line 62-63 of the spec doc) proposes `suggested_module` as a
singular nullable FK to `Module` + a separate `confidence_module` float.
That is wrong for this codebase: `Issue` has no direct module relationship
at all - modules attach to issues exclusively through the `ModuleIssue`
M2M join table (`plane.db.models.module`), and nothing in this fork
enforces "at most one module per issue" at the data layer. Modeling the
*suggestion* as a singular FK would be inventing a constraint the real
`Issue`/`Module` relationship doesn't have. Fixed here: `suggested_module_ids`
is a JSONField list (exactly the same shape as `suggested_assignee_ids`/
`suggested_label_ids`), and `confidence_modules` is a `{id: score}` JSONField
dict (same shape as `confidence_assignees`/`confidence_labels`). Exigence 2's
"0 ou 1 module suggere" cardinality rule is preserved at the LOGIC level
(`plane.utils.issue_triage_suggestion` never puts more than one entry in
`suggested_module_ids`) - only the wrong singular-FK *data type* was
rejected, not the "at most one" business rule itself.

NO M2M-THROUGH ON THE SUGGESTIONS THEMSELVES: matches the spec's own stated
reasoning for `suggested_assignee_ids`/`suggested_label_ids` (plain JSONField
list of UUIDs, not a real M2M) - an unresolved AI suggestion must never
pollute `IssueAssignee`/`IssueLabel`/`ModuleIssue` with unconfirmed data.

TWO FIELDS BEYOND THE SPEC'S OWN LITERAL LIST, BOTH NEEDED FOR CORRECT
PARTIAL-RESOLUTION/EXPIRY BOOKKEEPING (exigences 7 and 11) - `applied_fields`
alone cannot distinguish "field X was rejected" from "field X is still
pending" from "field X was never suggested to begin with":
  - `rejected_fields` (JSONField list) - mirrors `applied_fields`, records
    which of module/assignees/labels a human explicitly rejected via
    `.../resolve/`. Rejecting a field is a real, distinct terminal outcome
    (exigence 7 - "rejeter un champ ne declenche pas automatiquement une
    nouvelle proposition") and needs its own record, symmetric with
    `applied_fields`.
  - `expired_fields` (JSONField list) - records which field(s) a
    pre-application revalidation (exigence 11) found had a deleted/
    no-longer-project-scoped candidate. Kept separate from
    `applied_fields`/`rejected_fields` so a partially-expired suggestion's
    surviving fields can still show a clear reason for the ones that
    aren't actionable, rather than silently vanishing.

`suggested_*_ids`/`confidence_*` are NEVER mutated after generation - they
are the immutable record of "what the pipeline suggested". Resolution
outcomes (accepted/rejected/expired/still-pending) live entirely in
`applied_fields`/`rejected_fields`/`expired_fields`, so a field's current
state is always derivable without ambiguity: applied > rejected > expired >
(still pending, if the field has any suggested_*_ids at all) > (never
suggested for this field, if suggested_*_ids is empty).

EXPIRY GRANULARITY (exigence 11, deliberately resolved as the SIMPLER of
the two options the spec itself allows - "cette suggestion (ou toute la
ligne, au choix)" - passes through verbatim to this model's own author
instructions): `status` has exactly one `EXPIRED` value, applied to the
WHOLE row - not per-field - the moment ANY field being acted on (auto-apply
or a human's accept) is found, at application time, to reference a
deleted/out-of-project entity. This is simpler to reason about and test
than a per-field expiry state that would need its own enum, and matches
this model's own single `status` column shape (one value, not three
per-field ones).
"""

from django.conf import settings
from django.db import models

from .project import ProjectBaseModel


class IssueTriageSuggestionStatus(models.TextChoices):
    PENDING = "PENDING", "Pending"
    ACCEPTED = "ACCEPTED", "Accepted"
    PARTIALLY_ACCEPTED = "PARTIALLY_ACCEPTED", "Partially Accepted"
    REJECTED = "REJECTED", "Rejected"
    AUTO_APPLIED = "AUTO_APPLIED", "Auto Applied"
    EXPIRED = "EXPIRED", "Expired"


class IssueTriageSuggestion(ProjectBaseModel):
    """One row per issue (OneToOne, related_name `ai_triage_suggestion`) -
    same "no history, a regeneration overwrites this row" convention as
    `IssueEmbedding`/`IssueCommentSummary`."""

    issue = models.OneToOneField(
        "db.Issue", on_delete=models.CASCADE, related_name="ai_triage_suggestion"
    )

    # --- Suggested field values + per-value confidence (0-1) ---
    # See module docstring re: why module is list-shaped, not a singular FK.
    suggested_module_ids = models.JSONField(default=list, blank=True)
    suggested_assignee_ids = models.JSONField(default=list, blank=True)
    suggested_label_ids = models.JSONField(default=list, blank=True)
    confidence_modules = models.JSONField(default=dict, blank=True)
    confidence_assignees = models.JSONField(default=dict, blank=True)
    confidence_labels = models.JSONField(default=dict, blank=True)

    # UI explainability (exigence 4/5 - "base sur ces N tickets") - the
    # historical issues the similarity search matched against, regardless
    # of whether they ended up contributing a winning candidate for any
    # field.
    similar_issue_ids = models.JSONField(default=list, blank=True)

    status = models.CharField(
        max_length=30,
        choices=IssueTriageSuggestionStatus.choices,
        default=IssueTriageSuggestionStatus.PENDING,
    )
    # Fields (subset of "module"/"assignees"/"labels") actually auto-applied
    # or human-accepted - see module docstring for why this alone isn't
    # enough and `rejected_fields`/`expired_fields` exist alongside it.
    applied_fields = models.JSONField(default=list, blank=True)
    rejected_fields = models.JSONField(default=list, blank=True)
    expired_fields = models.JSONField(default=list, blank=True)

    # Provider-prefixed embedding model used to find the similar issues
    # this suggestion is based on (e.g. "openai/text-embedding-3-small") -
    # pipeline-versioning, same rationale as IssueEmbedding.model_name.
    generated_by_model = models.CharField(max_length=255, blank=True, default="")

    resolved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="issue_triage_suggestions_resolved",
    )
    resolved_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        verbose_name = "Issue Triage Suggestion"
        verbose_name_plural = "Issue Triage Suggestions"
        db_table = "issue_triage_suggestions"
        ordering = ("-created_at",)

    def __str__(self):
        return f"{self.issue_id} <-> ai-triage-suggestion:{self.status}"
