/**
 * Copyright (c) 2023-present Plane Software, Inc. and contributors
 * SPDX-License-Identifier: AGPL-3.0-only
 * See the LICENSE file for details.
 */

import { Settings2 } from "lucide-react";
import Link from "next/link";
// hooks
import { useIssueDetail } from "@/hooks/store/use-issue-detail";

type TIssueUser = {
  activityId: string;
  customUserName?: string;
};

export function IssueUser(props: TIssueUser) {
  const { activityId, customUserName } = props;
  // hooks
  const {
    activity: { getActivityById },
  } = useIssueDetail();

  const activity = getActivityById(activityId);

  if (!activity) return <></>;

  // Activity entries generated by the workflow rule engine attribute
  // `actor`/`actor_detail` to the rule's author (no dedicated bot user in
  // this codebase) - render a distinct "Automation" badge instead so it's
  // not misread as a manual change. See `IssueActivity.is_automation` in
  // apps/api/plane/db/models/issue.py.
  if (activity.is_automation) {
    return (
      <span className="inline-flex items-center gap-1 font-medium text-primary">
        <Settings2 className="h-3 w-3" aria-hidden="true" />
        Automation
      </span>
    );
  }

  return (
    <>
      {customUserName ? (
        <span className="font-medium text-primary">{customUserName}</span>
      ) : (
        <Link
          href={`/${activity?.workspace_detail?.slug}/profile/${activity?.actor_detail?.id}`}
          className="font-medium text-primary hover:underline"
        >
          {activity.actor_detail?.display_name}
        </Link>
      )}
    </>
  );
}
