# Generated by Django 4.2.30 on 2026-07-31 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_bulk_issue_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sub_issue_auto_close',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_issue_auto_close_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_issue_auto_close_projects', to='db.state'),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_issue_cascade_close',
            field=models.BooleanField(default=False),
        ),
    ]
