# Generated by Django 4.2.30 on 2026-07-31 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_sub_issue_automation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileasset',
            name='moved_from_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_moved_out', to='db.issue'),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='moved_from_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_moved_out', to='db.issue'),
        ),
        migrations.AddField(
            model_name='issuerelation',
            name='data_migrated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuerelation',
            name='data_migration_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20, null=True),
        ),
    ]
