# Generated by Django 4.2.30 on 2026-07-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_duplicate_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='actual_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='actual_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
