# Generated by Django 4.2.30 on 2026-07-31 15:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_cycle_manual_start_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='auto_rollover_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='is_auto_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CycleAutoScheduleConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('cadence_weeks', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('cooldown_days', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(14)])),
                ('lookahead_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('start_day_of_week', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('naming_template', models.CharField(default='Cycle {number}', max_length=255)),
                ('rollover_enabled', models.BooleanField(default=False)),
                ('next_auto_number', models.PositiveIntegerField(default=1)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_auto_schedule_config', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Cycle Auto Schedule Config',
                'verbose_name_plural': 'Cycle Auto Schedule Configs',
                'db_table': 'cycle_auto_schedule_configs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='cycle',
            name='generated_by_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_cycles', to='db.cycleautoscheduleconfig'),
        ),
    ]
