# Generated by Django 4.2.30 on 2026-07-31 16:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_cycle_auto_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeResponsibilitySetting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('assignment_mode', models.CharField(choices=[('fixed_owner', 'Fixed owner'), ('round_robin', 'Round robin')], default='round_robin', max_length=20)),
                ('escalation_timeout_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(1440)])),
                ('rotation_cursor', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('fixed_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_fixed_owner_settings', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_responsibility_setting', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Intake Responsibility Setting',
                'verbose_name_plural': 'Intake Responsibility Settings',
                'db_table': 'intake_responsibility_settings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='intakeissue',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intakeissue',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='intakeissue',
            name='assignment_source',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('fixed_owner', 'Fixed owner'), ('round_robin', 'Round robin')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='intakeissue',
            name='escalation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='intakeissue',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IntakeRotationMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_rotation_memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('responsibility_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotation_members', to='db.intakeresponsibilitysetting')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Intake Rotation Member',
                'verbose_name_plural': 'Intake Rotation Members',
                'db_table': 'intake_rotation_members',
                'ordering': ('sort_order',),
                'unique_together': {('responsibility_setting', 'member', 'deleted_at')},
            },
        ),
    ]
