# Generated by Django 4.2.30 on 2026-07-31 16:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.intake
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_triage_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeissue',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='intakeissue',
            name='submitter_ip_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='intakeissue',
            name='submitter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='IntakeForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description_html', models.TextField(blank=True, default='<p></p>')),
                ('token', models.CharField(db_index=True, default=plane.db.models.intake.get_intake_form_token, max_length=64, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('default_priority', models.CharField(blank=True, max_length=30, null=True)),
                ('show_priority_field', models.BooleanField(default=True)),
                ('show_labels_field', models.BooleanField(default=True)),
                ('allow_attachments', models.BooleanField(default=False)),
                ('max_attachments', models.PositiveSmallIntegerField(default=5)),
                ('require_submitter_name', models.BooleanField(default=False)),
                ('require_submitter_email', models.BooleanField(default=False)),
                ('send_confirmation_email', models.BooleanField(default=False)),
                ('success_message', models.TextField(blank=True, default='Thank you, your submission has been received.')),
                ('redirect_url', models.URLField(blank=True, null=True)),
                ('rate_limit_per_ip_per_hour', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('default_labels', models.ManyToManyField(blank=True, related_name='intake_forms', to='db.label')),
                ('default_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_forms', to='db.state')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Intake Form',
                'verbose_name_plural': 'Intake Forms',
                'db_table': 'intake_forms',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='intakeissue',
            name='intake_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='db.intakeform'),
        ),
    ]
