# Generated by Django 4.2.30 on 2026-07-31 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.intake_channel
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_intake_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeissue',
            name='external_participant_meta',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='intakeissue',
            name='external_thread_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SlackWorkspaceConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slack_team_id', models.CharField(max_length=64)),
                ('slack_team_name', models.CharField(blank=True, max_length=255)),
                ('bot_access_token', models.CharField(blank=True, max_length=300)),
                ('signing_secret', models.CharField(blank=True, max_length=300)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slack_connections_made', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Slack Workspace Connection',
                'verbose_name_plural': 'Slack Workspace Connections',
                'db_table': 'slack_workspace_connections',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SlackChannelProjectMapping',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slack_channel_id', models.CharField(max_length=64)),
                ('is_default_for_dm', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('slack_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_mappings', to='db.slackworkspaceconnection')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Slack Channel Project Mapping',
                'verbose_name_plural': 'Slack Channel Project Mappings',
                'db_table': 'slack_channel_project_mappings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IntakeMessageLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('channel_type', models.CharField(choices=[('EMAIL', 'Email'), ('SLACK', 'Slack')], max_length=10)),
                ('external_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('intake_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='db.intakeissue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Intake Message Log',
                'verbose_name_plural': 'Intake Message Logs',
                'db_table': 'intake_message_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='IntakeChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('channel_type', models.CharField(choices=[('EMAIL', 'Email'), ('SLACK', 'Slack')], max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Intake Channel',
                'verbose_name_plural': 'Intake Channels',
                'db_table': 'intake_channels',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InboundEmailAlias',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('local_part', models.CharField(db_index=True, default=plane.db.models.intake_channel.get_email_alias_local_part, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('intake_channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_alias', to='db.intakechannel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Inbound Email Alias',
                'verbose_name_plural': 'Inbound Email Aliases',
                'db_table': 'inbound_email_aliases',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='slackworkspaceconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('workspace',), name='one_active_slack_connection_per_workspace'),
        ),
        migrations.AddConstraint(
            model_name='slackchannelprojectmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slack_connection', 'slack_channel_id'), name='unique_slack_channel_per_connection'),
        ),
        migrations.AddConstraint(
            model_name='intakechannel',
            constraint=models.UniqueConstraint(condition=models.Q(('channel_type', 'EMAIL'), ('deleted_at__isnull', True), ('is_enabled', True)), fields=('project',), name='one_active_email_channel_per_project'),
        ),
    ]
