# Generated by Django 4.2.30 on 2026-07-31 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_omnichannel_intake_skeleton'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True, default='<p></p>')),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='PLANNED', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('health', models.CharField(blank=True, choices=[('on-track', 'On Track'), ('at-risk', 'At Risk'), ('off-track', 'Off Track')], max_length=20, null=True)),
                ('logo_props', models.JSONField(default=dict)),
                ('sort_order', models.FloatField(default=65535)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('external_source', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives_led', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
                'db_table': 'initiatives',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='health',
            field=models.CharField(blank=True, choices=[('on-track', 'On Track'), ('at-risk', 'At Risk'), ('off-track', 'Off Track')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_initiatives_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InitiativeProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='db.initiative')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_links', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_project_links', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Initiative Project',
                'verbose_name_plural': 'Initiative Projects',
                'db_table': 'initiative_projects',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InitiativeActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('verb', models.CharField(default='updated', max_length=255)),
                ('field', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='db.initiative')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_activities', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Initiative Activity',
                'verbose_name_plural': 'Initiative Activities',
                'db_table': 'initiative_activities',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='initiative',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='initiativeproject',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('initiative', 'project'), name='initiative_project_unique_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='initiativeproject',
            unique_together={('initiative', 'project', 'deleted_at')},
        ),
    ]
