# Generated by Django 4.2.30 on 2026-08-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0135_project_roadmap_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issuerelation',
            index=models.Index(fields=['issue', 'relation_type'], name='issue_rel_issue_type_idx'),
        ),
        migrations.AddIndex(
            model_name='issuerelation',
            index=models.Index(fields=['related_issue', 'relation_type'], name='issue_rel_related_type_idx'),
        ),
    ]
