# Generated by Django 4.2.30 on 2026-08-03 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0137_fix_project_user_property_rich_filters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notify_on_add', models.BooleanField(default=True)),
                ('notify_on_complete', models.BooleanField(default=True)),
                ('notify_on_cancel', models.BooleanField(default=True)),
                ('notify_by_email', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='db.issueview')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'View Subscription',
                'verbose_name_plural': 'View Subscriptions',
                'db_table': 'view_subscriptions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='viewsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue_view', 'subscriber'), name='view_subscription_unique_view_subscriber_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='viewsubscription',
            unique_together={('issue_view', 'subscriber', 'deleted_at')},
        ),
    ]
