# Generated by Django 4.2.30 on 2026-08-03 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0138_view_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalLanguageFilterQuery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('raw_query', models.TextField()),
                ('detected_language', models.CharField(blank=True, max_length=8)),
                ('resolved_filters', models.JSONField(default=dict)),
                ('restatement', models.TextField(blank=True)),
                ('unresolved_terms', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=10)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Natural Language Filter Query',
                'verbose_name_plural': 'Natural Language Filter Queries',
                'db_table': 'natural_language_filter_queries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='issueview',
            name='source_query',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='db.naturallanguagefilterquery'),
        ),
    ]
