# Generated by Django 4.2.30 on 2026-08-03 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0139_naturallanguagefilterquery_issueview_source_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycleuserproperties',
            name='chart_type',
            field=models.CharField(choices=[('burndown', 'Burn-down'), ('burnup', 'Burn-up')], default='burndown', max_length=10),
        ),
        migrations.AddField(
            model_name='cycleuserproperties',
            name='estimate_type',
            field=models.CharField(choices=[('issues', 'Issues'), ('points', 'Points')], default='issues', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='velocity_window_size',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
