# Generated by Django 4.2.30 on 2026-08-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0140_cycle_progress_and_project_velocity'),
    ]

    operations = [
        migrations.AddField(
            model_name='intakeissue',
            name='triaged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='issueactivity',
            index=models.Index(fields=['issue_id', 'field', 'created_at'], name='issue_activity_started_idx'),
        ),
    ]
