# Generated by Django 4.2.30 on 2026-08-04 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0142_dashboard_dashboardwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('ISSUE_CREATED', 'Issue created'), ('ISSUE_UPDATED', 'Issue updated'), ('STATE_CHANGED', 'State changed'), ('ASSIGNEE_CHANGED', 'Assignee changed'), ('PRIORITY_CHANGED', 'Priority changed'), ('LABEL_ADDED', 'Label added'), ('COMMENT_ADDED', 'Comment added')], max_length=30)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('execution_count', models.IntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workflow Rule',
                'verbose_name_plural': 'Workflow Rules',
                'db_table': 'workflow_rules',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='issueactivity',
            name='is_automation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='created_by_automation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhook',
            name='workflow_rule',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkflowAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('action_type', models.CharField(choices=[('SET_STATE', 'Set state'), ('SET_PRIORITY', 'Set priority'), ('SET_ASSIGNEES', 'Set assignees'), ('ADD_LABELS', 'Add labels'), ('REMOVE_LABELS', 'Remove labels'), ('SET_DUE_DATE', 'Set due date'), ('SET_START_DATE', 'Set start date'), ('POST_COMMENT', 'Post comment'), ('MENTION_USER', 'Mention user')], max_length=30)),
                ('action_config', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='db.workflowrule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Workflow Action',
                'verbose_name_plural': 'Workflow Actions',
                'db_table': 'workflow_actions',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowRuleExecutionLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('trigger_event', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], max_length=10)),
                ('actions_applied', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('chain_depth', models.PositiveIntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_rule_execution_logs', to='db.issue')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='db.workflowrule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Workflow Rule Execution Log',
                'verbose_name_plural': 'Workflow Rule Execution Logs',
                'db_table': 'workflow_rule_execution_logs',
                'ordering': ('-executed_at',),
                'indexes': [models.Index(fields=['rule', 'executed_at'], name='wf_rule_log_rule_exec_idx')],
            },
        ),
    ]
