# Generated by Django 4.2.30 on 2026-08-04 14:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0143_workflow_rule_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringIssueTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, default='')),
                ('description_html', models.TextField(blank=True, default='<p></p>')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('none', 'None')], default='none', max_length=30, verbose_name='Issue Priority')),
                ('frequency', models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10, null=True)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, default=list, size=None)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('month_of_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_occurrences', models.PositiveIntegerField(blank=True, null=True)),
                ('occurrences_generated', models.PositiveIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Recurring Issue Template',
                'verbose_name_plural': 'Recurring Issue Templates',
                'db_table': 'recurring_issue_templates',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='recurring_template_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RecurringIssueTemplateLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_issue_template_label', to='db.label')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_labels', to='db.recurringissuetemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Recurring Issue Template Label',
                'verbose_name_plural': 'Recurring Issue Template Labels',
                'db_table': 'recurring_issue_template_labels',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RecurringIssueTemplateAssignee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_issue_template_assignee_through', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_assignees', to='db.recurringissuetemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Recurring Issue Template Assignee',
                'verbose_name_plural': 'Recurring Issue Template Assignees',
                'db_table': 'recurring_issue_template_assignees',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='recurringissuetemplate',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='recurring_issue_template_assignee', through='db.RecurringIssueTemplateAssignee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringissuetemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='recurringissuetemplate',
            name='estimate_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_issue_template_estimates', to='db.estimatepoint'),
        ),
        migrations.AddField(
            model_name='recurringissuetemplate',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='recurring_issue_templates', through='db.RecurringIssueTemplateLabel', to='db.label'),
        ),
        migrations.AddField(
            model_name='recurringissuetemplate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='recurringissuetemplate',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_issue_template_state', to='db.state'),
        ),
        migrations.AddField(
            model_name='recurringissuetemplate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='recurringissuetemplate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='issue',
            name='recurring_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_issues', to='db.recurringissuetemplate'),
        ),
        migrations.AddConstraint(
            model_name='recurringissuetemplateassignee',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('template', 'assignee'), name='recurring_template_assignee_unique_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='recurringissuetemplateassignee',
            unique_together={('template', 'assignee', 'deleted_at')},
        ),
    ]
