# Generated by Django 4.2.30 on 2026-08-05 08:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0144_recurringissuetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sla_risk_level',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('applies_to_all_projects', models.BooleanField(default=False)),
                ('priority_filter', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=list, size=None)),
                ('state_group_filter', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('response_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('resolution_time_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('warning_threshold_percent', models.PositiveSmallIntegerField(default=75)),
                ('critical_threshold_percent', models.PositiveSmallIntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.FloatField(default=65535)),
                ('assignees', models.ManyToManyField(blank=True, related_name='sla_policies', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('labels', models.ManyToManyField(blank=True, related_name='sla_policies', to='db.label')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('projects', models.ManyToManyField(blank=True, related_name='sla_policies', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'SLA Policy',
                'verbose_name_plural': 'SLA Policies',
                'db_table': 'sla_policies',
                'ordering': ('sort_order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='IssueSLA',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sla_type', models.CharField(choices=[('response', 'Response'), ('resolution', 'Resolution')], max_length=20)),
                ('due_at', models.DateTimeField()),
                ('met_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('on_track', 'On track'), ('at_risk', 'At risk'), ('breached', 'Breached'), ('achieved', 'Achieved'), ('cancelled', 'Cancelled'), ('paused', 'Paused')], db_index=True, default='on_track', max_length=20)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_entries', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_sla_entries', to='db.slapolicy')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue SLA',
                'verbose_name_plural': 'Issue SLAs',
                'db_table': 'issue_slas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='issuesla',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('issue', 'sla_policy', 'sla_type'), name='issue_sla_unique_issue_policy_type_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='issuesla',
            unique_together={('issue', 'sla_policy', 'sla_type', 'deleted_at')},
        ),
    ]
