# Generated by Django 4.2.30 on 2026-08-06, hand-edited to add the seed
# RunPython step - see docs/feature-specs/08-api-webhooks-cli.md
# ("2. Rate limiting plus genereux") in plane-selfhost.
#
# Seeds the 3 real caller-type tiers this fork actually has a wiring point
# for (see `RateLimitTier`/`TieredSlidingWindowRateThrottle` docstrings for
# why `oauth_app`/`mcp_server` are deliberately NOT seeded here). No data
# migration backfills `APIToken.rate_limit_tier` on existing rows - a NULL
# FK resolves to the correct tier at read time via `APIToken.is_service`,
# see the throttle class for the resolution order. This mirrors how
# `is_service` itself is already branched on today with no equivalent
# backfill ever having been needed.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_rate_limit_tiers(apps, schema_editor):
    RateLimitTier = apps.get_model("db", "RateLimitTier")

    # personal_token keeps the exact 60/min default this fork already used
    # for every non-service token before this feature existed (see the old
    # `ApiKeyRateThrottle`/`API_KEY_RATE_LIMIT` env var default) - stays
    # backward-compatible for anyone already relying on that number.
    # service_account mirrors the old hardcoded `ServiceTokenRateThrottle`
    # value (300/min). session_web has no real DRF-level throttle applied
    # to it today (see BaseAPIView.get_throttles - this mechanism only
    # ever fires for X-Api-Key-authenticated /api/v1/ traffic) - this row
    # exists for forward-compatibility with the tier model's own design
    # (and a possible future session-level throttle) but is not currently
    # read by anything that enforces it, so its numbers are generous by
    # construction rather than derived from an existing enforced limit.
    tiers = [
        {"key": "session_web", "requests_per_minute": 300, "requests_per_hour": 10000},
        {"key": "personal_token", "requests_per_minute": 60, "requests_per_hour": 3600},
        {"key": "service_account", "requests_per_minute": 300, "requests_per_hour": 18000},
    ]
    for tier in tiers:
        RateLimitTier.objects.update_or_create(
            key=tier["key"],
            defaults={
                "requests_per_minute": tier["requests_per_minute"],
                "requests_per_hour": tier["requests_per_hour"],
                "is_default": True,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0146_workflowtransition_webhook_workflow_transition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apitoken",
            name="rate_limit_overridden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="rate_limit_overridden_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rate_limit_overrides_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="apitoken",
            name="rate_limit_override_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="RateLimitTier",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Last Modified At")),
                ("deleted_at", models.DateTimeField(blank=True, null=True, verbose_name="Deleted At")),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("key", models.SlugField(max_length=64, unique=True)),
                ("requests_per_minute", models.PositiveIntegerField(default=60)),
                ("requests_per_hour", models.PositiveIntegerField(default=1000)),
                ("complexity_points_per_hour", models.PositiveIntegerField(blank=True, null=True)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate Limit Tier",
                "verbose_name_plural": "Rate Limit Tiers",
                "db_table": "rate_limit_tiers",
                "ordering": ("key",),
            },
        ),
        migrations.AddField(
            model_name="apitoken",
            name="rate_limit_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="api_tokens",
                to="db.ratelimittier",
            ),
        ),
        migrations.RunPython(seed_rate_limit_tiers, reverse_code=migrations.RunPython.noop),
    ]
