# Generated by Django 4.2.30 on 2026-08-06 10:26
#
# NOTE (rate-limiting feature, category 8/feature 2): this migration was
# originally auto-generated together with 0147 as a single merged file,
# because this fork checkout is being worked on concurrently by another
# session building category 8/feature 1 (the flexible query layer) at the
# same time as this one. It has been split by hand into two independent,
# self-contained migrations so each feature keeps its own migration
# rather than the two being permanently entangled under one number - the
# operations below are unchanged from what `makemigrations` originally
# produced for that other feature's model changes
# (`Workspace.is_flexible_query_enabled`, `WorkspaceQuerySettings`,
# `FlexibleQueryLog`), only the `dependencies` pointer was updated to
# follow 0147 instead of 0146.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0147_rate_limit_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_flexible_query_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkspaceQuerySettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('max_depth', models.PositiveIntegerField(default=3)),
                ('max_cost', models.PositiveIntegerField(default=5000)),
                ('timeout_ms', models.PositiveIntegerField(default=5000)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flexible_query_settings', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Query Settings',
                'verbose_name_plural': 'Workspace Query Settings',
                'db_table': 'workspace_query_settings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FlexibleQueryLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('raw_query', models.JSONField(default=dict)),
                ('computed_cost', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('rejected', 'Rejected'), ('timeout', 'Timeout'), ('partial', 'Partial')], default='success', max_length=20)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flexible_query_logs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flexible_query_logs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Flexible Query Log',
                'verbose_name_plural': 'Flexible Query Logs',
                'db_table': 'flexible_query_logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='flex_query_log_ws_created_idx')],
            },
        ),
    ]
