# Generated by Django 4.2.30 on 2026-08-07 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0148_flexible_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiactivitylog',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apiactivitylog',
            name='source',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='apiactivitylog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_activity_logs', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='is_ephemeral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apitoken',
            name='scope',
            field=models.CharField(choices=[('read_write', 'Read & Write'), ('read_only', 'Read Only')], default='read_write', max_length=20),
        ),
        migrations.AddField(
            model_name='webhook',
            name='last_test_triggered_via',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='WorkspaceAPIExplorerSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('allow_members_execute', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_explorer_settings', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace API Explorer Settings',
                'verbose_name_plural': 'Workspace API Explorer Settings',
                'db_table': 'workspace_api_explorer_settings',
                'ordering': ('-created_at',),
            },
        ),
    ]
