# Generated by Django 4.2.30 on 2026-08-14 12:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import plane.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0149_apiactivitylog_duration_ms_apiactivitylog_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FigmaFileLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('figma_file_key', models.CharField(max_length=255)),
                ('figma_node_id', models.CharField(blank=True, max_length=255, null=True)),
                ('figma_file_name', models.CharField(blank=True, max_length=500)),
                ('figma_node_name', models.CharField(blank=True, max_length=500)),
                ('url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('sync_status_enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Figma File Link',
                'verbose_name_plural': 'Figma File Links',
                'db_table': 'figma_file_links',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FigmaSyncLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('direction', models.CharField(choices=[('plane_to_figma', 'Plane -> Figma'), ('figma_to_plane', 'Figma -> Plane')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Figma Sync Log',
                'verbose_name_plural': 'Figma Sync Logs',
                'db_table': 'figma_sync_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FigmaWorkspaceConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('figma_team_id', models.CharField(blank=True, max_length=255)),
                ('figma_team_name', models.CharField(blank=True, max_length=255)),
                ('figma_user_id', models.CharField(max_length=255)),
                ('figma_user_handle', models.CharField(blank=True, max_length=255)),
                ('access_token', plane.db.fields.EncryptedTextField()),
                ('refresh_token', plane.db.fields.EncryptedTextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Figma Workspace Connection',
                'verbose_name_plural': 'Figma Workspace Connections',
                'db_table': 'figma_workspace_connections',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SlackIssueThread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slack_channel_id', models.CharField(max_length=64)),
                ('slack_message_ts', models.CharField(max_length=32)),
                ('source', models.CharField(choices=[('created_from_slack', 'Created from Slack'), ('linked_manually', 'Linked manually')], default='linked_manually', max_length=20)),
            ],
            options={
                'verbose_name': 'Slack Issue Thread',
                'verbose_name_plural': 'Slack Issue Threads',
                'db_table': 'slack_issue_threads',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SlackNotificationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('event_type', models.CharField(max_length=32)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Slack Notification Log',
                'verbose_name_plural': 'Slack Notification Logs',
                'db_table': 'slack_notification_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SlackUserConnection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slack_user_id', models.CharField(max_length=64)),
                ('slack_user_display_name', models.CharField(blank=True, max_length=255)),
                ('verification_code', models.CharField(blank=True, db_index=True, max_length=16, null=True)),
                ('code_expires_at', models.DateTimeField(blank=True, null=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Slack User Connection',
                'verbose_name_plural': 'Slack User Connections',
                'db_table': 'slack_user_connections',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveConstraint(
            model_name='slackchannelprojectmapping',
            name='unique_slack_channel_per_connection',
        ),
        migrations.AddField(
            model_name='slackchannelprojectmapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slackchannelprojectmapping',
            name='notify_on',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), blank=True, default=list, size=5),
        ),
        migrations.AddField(
            model_name='slackchannelprojectmapping',
            name='slack_channel_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='slackworkspaceconnection',
            name='bot_user_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='slackworkspaceconnection',
            name='installation_method',
            field=models.CharField(choices=[('MANUAL_BOT_TOKEN', 'Manual bot token'), ('OAUTH', 'OAuth')], default='MANUAL_BOT_TOKEN', max_length=20),
        ),
        migrations.AddField(
            model_name='webhook',
            name='figma_link',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slackworkspaceconnection',
            name='bot_access_token',
            field=plane.db.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='slackworkspaceconnection',
            name='signing_secret',
            field=plane.db.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='slackchannelprojectmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slack_connection', 'slack_channel_id', 'project'), name='unique_slack_channel_per_connection_and_project'),
        ),
        migrations.AddField(
            model_name='slackuserconnection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='slackuserconnection',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='slackuserconnection',
            name='slack_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_connections', to='db.slackworkspaceconnection'),
        ),
        migrations.AddField(
            model_name='slackuserconnection',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='slackuserconnection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_user_connections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='slackuserconnection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='slacknotificationlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='slacknotificationlog',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='db.slackchannelprojectmapping'),
        ),
        migrations.AddField(
            model_name='slacknotificationlog',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='slacknotificationlog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='slacknotificationlog',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='slackissuethread',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='slackissuethread',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_threads', to='db.issue'),
        ),
        migrations.AddField(
            model_name='slackissuethread',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='slackissuethread',
            name='slack_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_threads', to='db.slackworkspaceconnection'),
        ),
        migrations.AddField(
            model_name='slackissuethread',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='slackissuethread',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='figmaworkspaceconnection',
            name='connected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='figma_connections_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='figmaworkspaceconnection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='figmaworkspaceconnection',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='figmaworkspaceconnection',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='figmaworkspaceconnection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='figmasynclog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='figmasynclog',
            name='file_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='db.figmafilelink'),
        ),
        migrations.AddField(
            model_name='figmasynclog',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='figmasynclog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='figmasynclog',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='figmafilelink',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='figmafilelink',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figma_links', to='db.issue'),
        ),
        migrations.AddField(
            model_name='figmafilelink',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='figmafilelink',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='figmafilelink',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.AddConstraint(
            model_name='slackuserconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slack_connection', 'slack_user_id'), name='unique_slack_user_per_connection'),
        ),
        migrations.AddIndex(
            model_name='slackissuethread',
            index=models.Index(fields=['issue'], name='slack_issue_issue_i_0067d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='slackissuethread',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('slack_channel_id', 'slack_message_ts'), name='unique_slack_thread_per_message'),
        ),
        migrations.AddConstraint(
            model_name='figmaworkspaceconnection',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True)), fields=('workspace',), name='unique_active_figma_connection_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='figmafilelink',
            index=models.Index(fields=['issue'], name='figma_file__issue_i_554f90_idx'),
        ),
        migrations.AddConstraint(
            model_name='figmafilelink',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('sync_status_enabled', True)), fields=('workspace', 'figma_file_key', 'figma_node_id'), name='unique_active_figma_sync_target'),
        ),
    ]
