# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""
Removes the legacy `plane.db.models.integration` package's tables
(`integrations`, `workspace_integrations`, `github_repositories`,
`github_repository_syncs`, `github_issue_syncs`, `github_comment_syncs`,
`slack_project_syncs`) - see
docs/feature-specs/07-integrations-git.md ("1. GitHub natif") in
plane-selfhost and the removal note in plane/db/models/__init__.py.

Written by hand (not autodetected as one step with the new
github_integration/gitlab_integration models) specifically so this
feature's brand-new `GithubRepository` model - a different shape, same
name - is generated by a later migration as a clean `CreateModel` rather
than the autodetector trying to ALTER the old table's columns into the
new shape (which is what happens if both are present in the same
`makemigrations` run: Django's autodetector matches models by
(app_label, model_name) and treats a same-named replacement as a
sequence of AddField/RemoveField edits on one continuously-evolving
model, not a delete-and-recreate - confirmed by running it that way
first and seeing exactly that confusing diff). Split into its own
migration, this step is a plain, unambiguous set of `DeleteModel`
operations - listed child-before-parent so Postgres never has to drop a
table another still-being-dropped table's FK points at within the same
migration.

Confirmed via exhaustive grep (see plane_fork_cat7_research_findings.md)
that these tables have zero real write path anywhere in the current
backend (no view/serializer/URL ever reachable references any of them) -
this is not a data-loss risk in any real deployment of this fork.
"""

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0150_category7_slack_figma"),
    ]

    operations = [
        migrations.DeleteModel(name="GithubCommentSync"),
        migrations.DeleteModel(name="GithubIssueSync"),
        migrations.DeleteModel(name="GithubRepositorySync"),
        migrations.DeleteModel(name="GithubRepository"),
        migrations.DeleteModel(name="SlackProjectSync"),
        migrations.DeleteModel(name="WorkspaceIntegration"),
        migrations.DeleteModel(name="Integration"),
    ]
