# Generated by Django 4.2.30 on 2026-08-17 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0154_agentprofile_apitoken_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAIConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('custom_openai_compatible', 'Custom (OpenAI-compatible)')], default='openai', max_length=30)),
                ('api_key', plane.db.fields.EncryptedTextField(blank=True, null=True)),
                ('api_base_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_ai_configs_connected', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace AI Config',
                'verbose_name_plural': 'Workspace AI Configs',
                'db_table': 'workspace_ai_configs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='workspaceaiconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace',), name='workspace_ai_config_unique_workspace_when_not_deleted'),
        ),
    ]
