# Generated by Django 4.2.30 on 2026-08-18 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0156_workspace_is_ai_summary_enabled_issuecommentsummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectupdate',
            name='ai_draft_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='ai_generation_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='ai_generation_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='ai_regeneration_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='ai_source_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='is_ai_assisted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ai_update_daily_generation_limit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ai_update_data_scope',
            field=models.CharField(choices=[('TITLES_STATES_ONLY', 'Titles, states, and assignees only'), ('FULL_DESCRIPTIONS', 'Titles, states, assignees, and full descriptions')], default='TITLES_STATES_ONLY', max_length=30),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_ai_update_draft_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='max_ai_update_regenerations',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], max_length=20)),
                ('provider', models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('custom_openai_compatible', 'Custom (OpenAI-compatible)')], max_length=30, null=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('token_usage', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_update_generation_logs', to=settings.AUTH_USER_MODEL)),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_generation_logs', to='db.projectupdate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'AI Generation Log',
                'verbose_name_plural': 'AI Generation Logs',
                'db_table': 'ai_generation_logs',
                'ordering': ('-created_at',),
            },
        ),
    ]
