# Generated by Django 4.2.30 on 2026-08-18 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0157_category9_ai_update_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueEmbedding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('embedding', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('embedding_dimension', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Embedding',
                'verbose_name_plural': 'Issue Embeddings',
                'db_table': 'issue_embeddings',
                'ordering': ('-created_at',),
            },
        ),
    ]
