# Generated by Django 4.2.30 on 2026-08-19 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0158_category9_issue_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_triage_auto_apply_assignee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_triage_auto_apply_labels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_triage_auto_apply_module',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_triage_confidence_threshold_assignee',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_triage_confidence_threshold_labels',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_triage_confidence_threshold_module',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_triage_max_labels_suggested',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='project',
            name='ai_triage_min_historical_issues',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='project',
            name='is_ai_triage_enabled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='webhook',
            name='issue_triage_suggestion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_ai_triage_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='IssueTriageSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('suggested_module_ids', models.JSONField(blank=True, default=list)),
                ('suggested_assignee_ids', models.JSONField(blank=True, default=list)),
                ('suggested_label_ids', models.JSONField(blank=True, default=list)),
                ('confidence_modules', models.JSONField(blank=True, default=dict)),
                ('confidence_assignees', models.JSONField(blank=True, default=dict)),
                ('confidence_labels', models.JSONField(blank=True, default=dict)),
                ('similar_issue_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('PARTIALLY_ACCEPTED', 'Partially Accepted'), ('REJECTED', 'Rejected'), ('AUTO_APPLIED', 'Auto Applied'), ('EXPIRED', 'Expired')], default='PENDING', max_length=30)),
                ('applied_fields', models.JSONField(blank=True, default=list)),
                ('rejected_fields', models.JSONField(blank=True, default=list)),
                ('expired_fields', models.JSONField(blank=True, default=list)),
                ('generated_by_model', models.CharField(blank=True, default='', max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_triage_suggestion', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_triage_suggestions_resolved', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Triage Suggestion',
                'verbose_name_plural': 'Issue Triage Suggestions',
                'db_table': 'issue_triage_suggestions',
                'ordering': ('-created_at',),
            },
        ),
    ]
