# Generated by Django 4.2.30 on 2026-08-19 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0159_category9_ai_triage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_duplicate_detection_enabled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='duplicate_detection_scope',
            field=models.CharField(choices=[('project', 'Current project only'), ('workspace', 'Entire workspace')], default='project', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='duplicate_detection_similarity_threshold',
            field=models.FloatField(default=0.82),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_duplicate_detection_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='IssueDuplicateSuggestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('similarity_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dismissed', 'Dismissed'), ('confirmed_duplicate', 'Confirmed Duplicate'), ('confirmed_related', 'Confirmed Related'), ('stale', 'Stale')], default='pending', max_length=30)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('issue_content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('suggested_issue_content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_suggestions', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_duplicate_suggestions_resolved', to=settings.AUTH_USER_MODEL)),
                ('suggested_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_suggested_by', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Issue Duplicate Suggestion',
                'verbose_name_plural': 'Issue Duplicate Suggestions',
                'db_table': 'issue_duplicate_suggestions',
                'ordering': ('-similarity_score',),
                'indexes': [models.Index(fields=['issue', 'status'], name='issue_dup_sugg_iss_st_idx'), models.Index(fields=['suggested_issue', 'status'], name='issue_dup_sugg_cand_st_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='issueduplicatesuggestion',
            constraint=models.UniqueConstraint(fields=('issue', 'suggested_issue'), name='issue_duplicate_suggestion_unique_pair'),
        ),
    ]
