# Generated by Django 4.2.30 on 2026-08-19 14:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0160_project_is_duplicate_detection_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='digest_feature_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_digest_llm_enrichment_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DigestRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATED', 'Generated'), ('SENT', 'Sent'), ('SKIPPED_EMPTY', 'Skipped (Empty)'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('generation_method', models.CharField(choices=[('TEMPLATE', 'Template'), ('LLM', 'LLM')], default='TEMPLATE', max_length=10)),
                ('summary_text', models.TextField(blank=True, default='')),
                ('audio_file', models.URLField(blank=True, max_length=800, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('item_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_runs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_runs', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Digest Run',
                'verbose_name_plural': 'Digest Runs',
                'db_table': 'digest_runs',
                'ordering': ('-period_end',),
            },
        ),
        migrations.CreateModel(
            name='DigestPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='DAILY', max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_of_day', models.TimeField(default=datetime.time(8, 0))),
                ('scope', models.CharField(choices=[('ALL_PROJECTS', 'All Projects'), ('FAVORITES_ONLY', 'Favorites Only'), ('CUSTOM', 'Custom')], default='ALL_PROJECTS', max_length=20)),
                ('send_in_app', models.BooleanField(default=True)),
                ('send_email', models.BooleanField(default=True)),
                ('send_audio', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('custom_projects', models.ManyToManyField(blank=True, related_name='digest_preferences_custom', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_preferences', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digest_preferences', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Digest Preference',
                'verbose_name_plural': 'Digest Preferences',
                'db_table': 'digest_preferences',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DigestItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item_type', models.CharField(choices=[('ISSUE_CREATED', 'Issue Created'), ('ISSUE_COMPLETED', 'Issue Completed'), ('ISSUE_STATE_CHANGED', 'Issue State Changed'), ('COMMENT_MENTION', 'Comment Mention'), ('CYCLE_STARTED', 'Cycle Started'), ('CYCLE_COMPLETED', 'Cycle Completed'), ('CYCLE_SCOPE_CHANGED', 'Cycle Scope Changed')], max_length=30)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('position', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_items_authored', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_items', to='db.cycle')),
                ('digest_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.digestrun')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='digest_items', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Digest Item',
                'verbose_name_plural': 'Digest Items',
                'db_table': 'digest_items',
                'ordering': ('digest_run_id', 'position'),
            },
        ),
        migrations.AddConstraint(
            model_name='digestrun',
            constraint=models.UniqueConstraint(fields=('user', 'workspace', 'period_start', 'period_end'), name='digest_run_unique_user_workspace_period'),
        ),
        migrations.AlterUniqueTogether(
            name='digestpreference',
            unique_together={('user', 'workspace')},
        ),
    ]
