# Generated by Django 4.2.30 on 2026-08-20 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.ai_chat
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0161_category9_digest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('context_type', models.CharField(choices=[('workspace', 'Workspace'), ('project', 'Project'), ('issue', 'Issue'), ('cycle', 'Cycle'), ('module', 'Module'), ('page', 'Page')], max_length=20)),
                ('context_object_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(choices=[('command_palette', 'Command Palette'), ('comment_mention', 'Comment Mention')], default='command_palette', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'AI Conversation',
                'verbose_name_plural': 'AI Conversations',
                'db_table': 'ai_conversations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='project',
            name='is_ai_assistant_enabled',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='ai_assistant_max_messages_per_user_per_hour',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='is_ai_assistant_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AIMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10)),
                ('content', models.TextField(blank=True, default='')),
                ('mode', models.CharField(choices=[('ask', 'Ask'), ('propose', 'Propose')], default='ask', max_length=10)),
                ('token_count_input', models.PositiveIntegerField(blank=True, null=True)),
                ('token_count_output', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=12)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='db.aiconversation')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'AI Message',
                'verbose_name_plural': 'AI Messages',
                'db_table': 'ai_messages',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='aiconversation',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.CreateModel(
            name='AIChangeProposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('target_model', models.CharField(choices=[('issue', 'Issue'), ('cycle', 'Cycle'), ('module', 'Module'), ('page', 'Page')], max_length=10)),
                ('target_object_id', models.UUIDField()),
                ('field_name', models.CharField(max_length=100)),
                ('proposed_value', models.JSONField(blank=True, default=dict)),
                ('previous_value', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(default=plane.db.models.ai_chat.default_proposal_expiry)),
                ('applied_activity_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='db.aimessage')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_change_proposals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'AI Change Proposal',
                'verbose_name_plural': 'AI Change Proposals',
                'db_table': 'ai_change_proposals',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='issuecomment',
            name='ai_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_comments', to='db.aiconversation'),
        ),
        migrations.AddIndex(
            model_name='aimessage',
            index=models.Index(fields=['conversation', 'created_at'], name='ai_message_conv_created_idx'),
        ),
        migrations.AddIndex(
            model_name='aiconversation',
            index=models.Index(fields=['workspace', 'created_by', '-created_at'], name='ai_conv_workspace_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='aichangeproposal',
            index=models.Index(fields=['status', 'expires_at'], name='ai_proposal_status_expiry_idx'),
        ),
    ]
