# Generated by Django 4.2.30 on 2026-08-20 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0162_category9_ai_chat_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageReaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('reaction', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_reactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_reactions', to='db.page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_page_reactions', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Page Reaction',
                'verbose_name_plural': 'Page Reactions',
                'db_table': 'page_reactions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='pagereaction',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('page', 'actor', 'reaction'), name='page_reaction_unique_page_actor_reaction_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='pagereaction',
            unique_together={('page', 'actor', 'reaction', 'deleted_at')},
        ),
    ]
