# Generated by Django 4.2.30 on 2026-08-20 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0163_pagereaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCollection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('logo_props', models.JSONField(default=dict)),
                ('sort_order', models.FloatField(default=65535)),
            ],
            options={
                'verbose_name': 'Page Collection',
                'verbose_name_plural': 'Page Collections',
                'db_table': 'page_collections',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='workspace',
            name='wiki_root_creation_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['workspace', 'is_global'], name='page_workspace_is_global_idx'),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='db.pagecollection'),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='pagecollection',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_collections', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='page',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='db.pagecollection'),
        ),
        migrations.AddIndex(
            model_name='pagecollection',
            index=models.Index(fields=['workspace', 'parent'], name='pgcoll_wksp_parent_idx'),
        ),
    ]
