# Generated by Django 4.2.30 on 2026-08-21 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0165_pagecomment_pagecommentreaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreference',
            name='page_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='page_edits',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='page_mentions',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PageSubscriber',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('subscribed_manually', models.BooleanField(default=True)),
                ('unsubscribed_manually', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_subscribers', to='db.page')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_page_subscribers', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Page Subscriber',
                'verbose_name_plural': 'Page Subscribers',
                'db_table': 'page_subscribers',
                'ordering': ('-created_at',),
                'unique_together': {('page', 'subscriber')},
            },
        ),
        migrations.CreateModel(
            name='PageActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('verb', models.CharField(default='updated', max_length=255, verbose_name='Action')),
                ('field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Field Name')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Old Value')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='New Value')),
                ('epoch', models.FloatField(blank=True, null=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_activities', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='db.page')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_activities', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Page Activity',
                'verbose_name_plural': 'Page Activities',
                'db_table': 'page_activities',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['page', '-created_at'], name='page_activity_page_created_idx')],
            },
        ),
    ]
