# Generated by Django 4.2.30 on 2026-08-22 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0166_usernotificationpreference_page_comments_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceAuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('actor_email_snapshot', models.CharField(blank=True, max_length=255)),
                ('target_email_snapshot', models.CharField(blank=True, max_length=255)),
                ('target_type', models.CharField(blank=True, max_length=32)),
                ('target_id', models.CharField(blank=True, max_length=255)),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('MEMBER_INVITED', 'Member Invited'), ('MEMBER_INVITE_REVOKED', 'Member Invite Revoked'), ('MEMBER_INVITE_ACCEPTED', 'Member Invite Accepted'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_ROLE_CHANGED', 'Member Role Changed'), ('MEMBER_DEACTIVATED', 'Member Deactivated'), ('API_TOKEN_CREATED', 'Api Token Created'), ('API_TOKEN_REVOKED', 'Api Token Revoked'), ('WEBHOOK_CREATED', 'Webhook Created'), ('WEBHOOK_UPDATED', 'Webhook Updated'), ('WEBHOOK_DELETED', 'Webhook Deleted'), ('OAUTH_CONFIG_UPDATED', 'Oauth Config Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_OWNER_ASSIGNED', 'Project Owner Assigned'), ('PROJECT_OWNER_REVOKED', 'Project Owner Revoked'), ('OWNERSHIP_TRANSFERRED', 'Ownership Transferred'), ('WORKSPACE_DELETED', 'Workspace Deleted')], db_index=True, max_length=64)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Workspace Audit Log',
                'verbose_name_plural': 'Workspace Audit Logs',
                'db_table': 'workspace_audit_logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='projectmember',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhook',
            name='workspace_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exporterhistory',
            name='type',
            field=models.CharField(choices=[('issue_exports', 'Issue Exports'), ('issue_worklogs', 'Issue Worklogs'), ('audit_log_exports', 'Audit Log Exports')], default='issue_exports', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='projectmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_owner', True)), fields=('project',), name='unique_project_owner'),
        ),
        migrations.AddField(
            model_name='workspaceauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceauditlog',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='workspaceauditlog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspaceauditlog',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='workspaceauditlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='db.workspace'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['workspace', '-created_at'], name='workspace_a_workspa_7c8bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['workspace', 'event_type'], name='workspace_a_workspa_13106e_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['actor', '-created_at'], name='workspace_a_actor_i_be06c4_idx'),
        ),
        migrations.AddIndex(
            model_name='workspaceauditlog',
            index=models.Index(fields=['target_user', '-created_at'], name='workspace_a_target__e6c9e7_idx'),
        ),
    ]
