# Generated by Django 4.2.30 on 2026-08-23 15:06

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import plane.db.models.workspace
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0168_category11_owner_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_authenticated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='last_workspace_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspaceauditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('MEMBER_INVITED', 'Member Invited'), ('MEMBER_INVITE_REVOKED', 'Member Invite Revoked'), ('MEMBER_INVITE_ACCEPTED', 'Member Invite Accepted'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_ROLE_CHANGED', 'Member Role Changed'), ('MEMBER_DEACTIVATED', 'Member Deactivated'), ('API_TOKEN_CREATED', 'Api Token Created'), ('API_TOKEN_REVOKED', 'Api Token Revoked'), ('WEBHOOK_CREATED', 'Webhook Created'), ('WEBHOOK_UPDATED', 'Webhook Updated'), ('WEBHOOK_DELETED', 'Webhook Deleted'), ('OAUTH_CONFIG_UPDATED', 'Oauth Config Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_OWNER_ASSIGNED', 'Project Owner Assigned'), ('PROJECT_OWNER_REVOKED', 'Project Owner Revoked'), ('OWNERSHIP_TRANSFERRED', 'Ownership Transferred'), ('WORKSPACE_DELETED', 'Workspace Deleted'), ('SECURITY_POLICY_UPDATED', 'Security Policy Updated'), ('VERIFIED_DOMAIN_ADDED', 'Verified Domain Added'), ('DOMAIN_VERIFICATION_STATUS_CHANGED', 'Domain Verification Status Changed'), ('VERIFIED_DOMAIN_REMOVED', 'Verified Domain Removed')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='WorkspaceSecurityPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('enforce_sso_only', models.BooleanField(default=False)),
                ('member_invite_restriction', models.CharField(choices=[('OWNER_ONLY', 'Owner only'), ('ADMINS_AND_ABOVE', 'Admins and above'), ('ADMINS_AND_MEMBERS', 'Admins and Members')], default='ADMINS_AND_ABOVE', max_length=32)),
                ('allowed_auth_methods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('EMAIL_PASSWORD', 'Email / Password'), ('MAGIC_LINK', 'Magic Link / OTP'), ('GOOGLE', 'Google OAuth'), ('GITHUB', 'GitHub OAuth')], max_length=32), blank=True, default=plane.db.models.workspace.get_default_allowed_auth_methods, size=None)),
                ('session_timeout_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('force_reauth_for_sensitive_actions', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_policy', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Security Policy',
                'verbose_name_plural': 'Workspace Security Policies',
                'db_table': 'workspace_security_policies',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceVerifiedDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('verification_method', models.CharField(choices=[('DNS_TXT', 'DNS TXT record'), ('HTML_FILE', 'HTML file upload')], max_length=16)),
                ('verification_token', models.CharField(max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verified_domains', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Verified Domain',
                'verbose_name_plural': 'Workspace Verified Domains',
                'db_table': 'workspace_verified_domains',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['workspace'], name='workspace_v_workspa_7a63d4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workspaceverifieddomain',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('workspace', 'domain'), name='workspace_verified_domain_unique_workspace_domain_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceverifieddomain',
            unique_together={('workspace', 'domain', 'deleted_at')},
        ),
    ]
