# Generated by Django 4.2.30 on 2026-08-23 21:05, hand-edited to add the
# `scim_sync` RateLimitTier seed RunPython step - see
# docs/feature-specs/11-admin-security-sso.md ("2. SCIM 2.0 natif") in
# plane-selfhost, exigence 12, same "schema + seed in one migration" shape
# as this fork's own precedent for the 3 original tiers
# (0147_rate_limit_tier.py).
#
# Category 11 (docs/feature-specs/11-admin-security-sso.md in
# plane-selfhost), feature 2 "SCIM 2.0 natif".
#
# Rate-limit design decision: `RateLimitTier` (category 8's model) is
# REUSED here for its concept and its `key`-is-a-free-form-slug design
# (explicitly reserved for exactly this kind of future addition, see that
# model's own docstring) - but `TieredSlidingWindowRateThrottle`
# (plane.api.rate_limit) itself is NOT reused, because it is hard-coupled
# to `APIToken` (plaintext `token=` lookup, `X-Api-Key` header,
# `is_service`/`rate_limit_tier`/override fields that `SCIMToken` does not
# and per this feature's own spec should not have). A new
# `plane.scim.throttling.SCIMTieredRateThrottle` resolves this SAME
# `scim_sync` tier row from the already-authenticated `SCIMToken` on
# `request.auth` instead, reusing the identical Redis sliding-window Lua
# script for behavioral consistency. See that module's own docstring.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def seed_scim_rate_limit_tier(apps, schema_editor):
    RateLimitTier = apps.get_model("db", "RateLimitTier")
    # Exigence 12 - "quota dédié plus généreux adapté aux synchronisations
    # périodiques d'annuaire". Deliberately more generous than
    # `personal_token` (60/min, 3600/hour) - a directory sync sweeping a
    # few hundred/thousand users in `startIndex`/`count` pages can
    # legitimately burst well above a personal token's own budget.
    RateLimitTier.objects.update_or_create(
        key="scim_sync",
        defaults={
            "requests_per_minute": 120,
            "requests_per_hour": 5000,
            "is_default": True,
        },
    )


def unseed_scim_rate_limit_tier(apps, schema_editor):
    RateLimitTier = apps.get_model("db", "RateLimitTier")
    RateLimitTier.objects.filter(key="scim_sync").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0170_alter_account_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCIMToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('label', models.CharField(default='SCIM Token', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SCIM Token',
                'verbose_name_plural': 'SCIM Tokens',
                'db_table': 'scim_tokens',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='scim_external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='scim_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workspaceauditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('MEMBER_INVITED', 'Member Invited'), ('MEMBER_INVITE_REVOKED', 'Member Invite Revoked'), ('MEMBER_INVITE_ACCEPTED', 'Member Invite Accepted'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_ROLE_CHANGED', 'Member Role Changed'), ('MEMBER_DEACTIVATED', 'Member Deactivated'), ('API_TOKEN_CREATED', 'Api Token Created'), ('API_TOKEN_REVOKED', 'Api Token Revoked'), ('WEBHOOK_CREATED', 'Webhook Created'), ('WEBHOOK_UPDATED', 'Webhook Updated'), ('WEBHOOK_DELETED', 'Webhook Deleted'), ('OAUTH_CONFIG_UPDATED', 'Oauth Config Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_OWNER_ASSIGNED', 'Project Owner Assigned'), ('PROJECT_OWNER_REVOKED', 'Project Owner Revoked'), ('OWNERSHIP_TRANSFERRED', 'Ownership Transferred'), ('WORKSPACE_DELETED', 'Workspace Deleted'), ('SECURITY_POLICY_UPDATED', 'Security Policy Updated'), ('VERIFIED_DOMAIN_ADDED', 'Verified Domain Added'), ('DOMAIN_VERIFICATION_STATUS_CHANGED', 'Domain Verification Status Changed'), ('VERIFIED_DOMAIN_REMOVED', 'Verified Domain Removed'), ('SCIM_USER_CREATED', 'Scim User Created'), ('SCIM_USER_UPDATED', 'Scim User Updated'), ('SCIM_USER_DEACTIVATED', 'Scim User Deactivated'), ('SCIM_SYNC_ERROR', 'Scim Sync Error')], db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='workspacemember',
            constraint=models.UniqueConstraint(condition=models.Q(('scim_external_id__isnull', False)), fields=('workspace', 'scim_external_id'), name='workspace_member_unique_workspace_scim_external_id_when_set'),
        ),
        migrations.AddField(
            model_name='scimtoken',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='scimtoken',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='scimtoken',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_tokens', to='db.workspace'),
        ),
        migrations.RunPython(seed_scim_rate_limit_tier, reverse_code=unseed_scim_rate_limit_tier),
    ]
