# Generated by Django 4.2.30 on 2026-08-24 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0171_category11_scim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('category', models.CharField(choices=[('ISSUE', 'Issue'), ('CYCLE', 'Cycle'), ('MODULE', 'Module'), ('PAGE', 'Page'), ('VIEW', 'View'), ('WORKSPACE', 'Workspace')], db_index=True, max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('supported_conditions', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'rbac_permissions',
                'ordering': ('category', 'key'),
            },
        ),
        migrations.CreateModel(
            name='PermissionScheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_schemes', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Permission Scheme',
                'verbose_name_plural': 'Permission Schemes',
                'db_table': 'rbac_permission_schemes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='WorkspaceRole',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('legacy_role_value', models.IntegerField(blank=True, null=True)),
                ('is_owner_equivalent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rbac_roles', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Role',
                'verbose_name_plural': 'Workspace Roles',
                'db_table': 'rbac_workspace_roles',
                'ordering': ('-is_system', 'name'),
            },
        ),
        migrations.AlterField(
            model_name='workspaceauditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('MEMBER_INVITED', 'Member Invited'), ('MEMBER_INVITE_REVOKED', 'Member Invite Revoked'), ('MEMBER_INVITE_ACCEPTED', 'Member Invite Accepted'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_ROLE_CHANGED', 'Member Role Changed'), ('MEMBER_DEACTIVATED', 'Member Deactivated'), ('API_TOKEN_CREATED', 'Api Token Created'), ('API_TOKEN_REVOKED', 'Api Token Revoked'), ('WEBHOOK_CREATED', 'Webhook Created'), ('WEBHOOK_UPDATED', 'Webhook Updated'), ('WEBHOOK_DELETED', 'Webhook Deleted'), ('OAUTH_CONFIG_UPDATED', 'Oauth Config Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_OWNER_ASSIGNED', 'Project Owner Assigned'), ('PROJECT_OWNER_REVOKED', 'Project Owner Revoked'), ('OWNERSHIP_TRANSFERRED', 'Ownership Transferred'), ('WORKSPACE_DELETED', 'Workspace Deleted'), ('SECURITY_POLICY_UPDATED', 'Security Policy Updated'), ('VERIFIED_DOMAIN_ADDED', 'Verified Domain Added'), ('DOMAIN_VERIFICATION_STATUS_CHANGED', 'Domain Verification Status Changed'), ('VERIFIED_DOMAIN_REMOVED', 'Verified Domain Removed'), ('SCIM_USER_CREATED', 'Scim User Created'), ('SCIM_USER_UPDATED', 'Scim User Updated'), ('SCIM_USER_DEACTIVATED', 'Scim User Deactivated'), ('SCIM_SYNC_ERROR', 'Scim Sync Error'), ('ROLE_DEFINITION_CHANGED', 'Role Definition Changed')], db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='workspacemember',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='db.workspacerole'),
        ),
        migrations.CreateModel(
            name='WorkspaceRoleScheme',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_links', to='db.workspacerole')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_links', to='db.permissionscheme')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Workspace Role Scheme',
                'verbose_name_plural': 'Workspace Role Schemes',
                'db_table': 'rbac_workspace_role_schemes',
                'unique_together': {('role', 'scheme')},
            },
        ),
        migrations.CreateModel(
            name='PermissionSchemeItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('condition', models.CharField(choices=[('NONE', 'None'), ('CREATOR_ONLY', 'Creator Only'), ('PROJECT_LEAD_ONLY', 'Project Lead Only')], default='NONE', max_length=32)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_items', to='db.permission')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.permissionscheme')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Permission Scheme Item',
                'verbose_name_plural': 'Permission Scheme Items',
                'db_table': 'rbac_permission_scheme_items',
                'ordering': ('permission__category', 'permission__key'),
                'unique_together': {('scheme', 'permission')},
            },
        ),
    ]
