# Generated by Django 4.2.30 on 2026-08-24 20:11

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.functions.comparison
import django.db.models.functions.text
import plane.db.models.functions


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0174_category12_search_trigram_extensions'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(plane.db.models.functions.ImmutableUnaccent(django.db.models.functions.text.Lower('name')), name='gin_trgm_ops'), name='issue_name_trgm_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(plane.db.models.functions.ImmutableUnaccent(django.db.models.functions.text.Lower('description_stripped')), name='gin_trgm_ops'), name='issue_desc_trgm_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='issuecomment',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(plane.db.models.functions.ImmutableUnaccent(django.db.models.functions.text.Lower('comment_stripped')), name='gin_trgm_ops'), name='issue_comment_trgm_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(plane.db.models.functions.ImmutableUnaccent(django.db.models.functions.text.Lower(plane.db.models.functions.ImmutableConcat(django.db.models.functions.comparison.Coalesce('first_name', models.Value('')), models.Value(' '), django.db.models.functions.comparison.Coalesce('last_name', models.Value('')), models.Value(' '), django.db.models.functions.comparison.Coalesce('display_name', models.Value('')), models.Value(' '), django.db.models.functions.comparison.Coalesce('email', models.Value(''))))), name='gin_trgm_ops'), name='user_search_trgm_gin_idx'),
        ),
    ]
