# Generated by Django 4.2.30 on 2026-08-25 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0175_issue_issue_name_trgm_gin_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationpreference',
            name='push_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='push_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='push_issue_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='push_mention',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='push_property_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='push_state_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usernotificationpreference',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workspaceauditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('MEMBER_INVITED', 'Member Invited'), ('MEMBER_INVITE_REVOKED', 'Member Invite Revoked'), ('MEMBER_INVITE_ACCEPTED', 'Member Invite Accepted'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_ROLE_CHANGED', 'Member Role Changed'), ('MEMBER_DEACTIVATED', 'Member Deactivated'), ('API_TOKEN_CREATED', 'Api Token Created'), ('API_TOKEN_REVOKED', 'Api Token Revoked'), ('WEBHOOK_CREATED', 'Webhook Created'), ('WEBHOOK_UPDATED', 'Webhook Updated'), ('WEBHOOK_DELETED', 'Webhook Deleted'), ('OAUTH_CONFIG_UPDATED', 'Oauth Config Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_OWNER_ASSIGNED', 'Project Owner Assigned'), ('PROJECT_OWNER_REVOKED', 'Project Owner Revoked'), ('OWNERSHIP_TRANSFERRED', 'Ownership Transferred'), ('WORKSPACE_DELETED', 'Workspace Deleted'), ('SECURITY_POLICY_UPDATED', 'Security Policy Updated'), ('VERIFIED_DOMAIN_ADDED', 'Verified Domain Added'), ('DOMAIN_VERIFICATION_STATUS_CHANGED', 'Domain Verification Status Changed'), ('VERIFIED_DOMAIN_REMOVED', 'Verified Domain Removed'), ('SCIM_USER_CREATED', 'Scim User Created'), ('SCIM_USER_UPDATED', 'Scim User Updated'), ('SCIM_USER_DEACTIVATED', 'Scim User Deactivated'), ('SCIM_SYNC_ERROR', 'Scim Sync Error'), ('ROLE_DEFINITION_CHANGED', 'Role Definition Changed'), ('PUSH_CONFIG_UPDATED', 'Push Config Updated')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='PushNotificationSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('device_type', models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android'), ('IOS', 'iOS')], max_length=10)),
                ('endpoint', models.URLField(blank=True, max_length=1000, null=True)),
                ('p256dh_key', models.CharField(blank=True, max_length=255, null=True)),
                ('auth_key', models.CharField(blank=True, max_length=255, null=True)),
                ('push_token', models.CharField(blank=True, max_length=500, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Notification Subscription',
                'verbose_name_plural': 'Push Notification Subscriptions',
                'db_table': 'push_notification_subscriptions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='pushnotificationsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('endpoint__isnull', False)), fields=('user', 'endpoint'), name='push_subscription_unique_user_endpoint_when_active'),
        ),
        migrations.AddConstraint(
            model_name='pushnotificationsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('push_token__isnull', False)), fields=('user', 'push_token'), name='push_subscription_unique_user_push_token_when_active'),
        ),
    ]
