# Generated by Django 4.2.30 on 2026-08-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0177_idempotencykey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='is_offline_sync_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
