# Generated by Django 4.2.30 on 2026-08-27 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0182_webhook_issue_worklog_webhook_timesheet_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo_props', models.JSONField(default=dict)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('prospect', 'Prospect'), ('churned', 'Churned')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_customers', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requested_at', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_requests', to='db.customer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_customer_requests', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Customer Request',
                'verbose_name_plural': 'Customer Requests',
                'db_table': 'customer_requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='webhook',
            name='customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhook',
            name='customer_request',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CustomerRequestIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_request_issues', to='db.customerrequest')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_customer_requests', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Customer Request Issue',
                'verbose_name_plural': 'Customer Request Issues',
                'db_table': 'customer_request_issues',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['customer_request', 'issue'], name='customer_req_issue_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='customerrequestissue',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('customer_request', 'issue'), name='customer_request_issue_unique_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='customerrequestissue',
            unique_together={('customer_request', 'issue', 'deleted_at')},
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['customer'], name='customer_request_customer_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['workspace'], name='customer_workspace_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('workspace'), condition=models.Q(('deleted_at__isnull', True)), name='customer_unique_name_ci_per_workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('workspace', 'name', 'deleted_at')},
        ),
    ]
