# Generated by Django 4.2.30 on 2026-08-27 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0184_pagetemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailIssueThread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('outbound_message_id', models.CharField(db_index=True, max_length=255)),
                ('source', models.CharField(choices=[('created_from_email', 'Created from email'), ('linked_manually', 'Linked manually')], default='created_from_email', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('intake_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='db.intakechannel')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_threads', to='db.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Email Issue Thread',
                'verbose_name_plural': 'Email Issue Threads',
                'db_table': 'email_issue_threads',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['intake_channel'], name='email_issue_intake__48ed90_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='emailissuethread',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('outbound_message_id',), name='unique_active_outbound_message_id'),
        ),
    ]
