# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0185_emailissuethread_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceauditlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('MEMBER_INVITED', 'Member Invited'), ('MEMBER_INVITE_REVOKED', 'Member Invite Revoked'), ('MEMBER_INVITE_ACCEPTED', 'Member Invite Accepted'), ('MEMBER_REMOVED', 'Member Removed'), ('MEMBER_ROLE_CHANGED', 'Member Role Changed'), ('MEMBER_DEACTIVATED', 'Member Deactivated'), ('API_TOKEN_CREATED', 'Api Token Created'), ('API_TOKEN_REVOKED', 'Api Token Revoked'), ('WEBHOOK_CREATED', 'Webhook Created'), ('WEBHOOK_UPDATED', 'Webhook Updated'), ('WEBHOOK_DELETED', 'Webhook Deleted'), ('OAUTH_CONFIG_UPDATED', 'Oauth Config Updated'), ('PROJECT_DELETED', 'Project Deleted'), ('PROJECT_OWNER_ASSIGNED', 'Project Owner Assigned'), ('PROJECT_OWNER_REVOKED', 'Project Owner Revoked'), ('OWNERSHIP_TRANSFERRED', 'Ownership Transferred'), ('WORKSPACE_DELETED', 'Workspace Deleted'), ('SECURITY_POLICY_UPDATED', 'Security Policy Updated'), ('VERIFIED_DOMAIN_ADDED', 'Verified Domain Added'), ('DOMAIN_VERIFICATION_STATUS_CHANGED', 'Domain Verification Status Changed'), ('VERIFIED_DOMAIN_REMOVED', 'Verified Domain Removed'), ('SCIM_USER_CREATED', 'Scim User Created'), ('SCIM_USER_UPDATED', 'Scim User Updated'), ('SCIM_USER_DEACTIVATED', 'Scim User Deactivated'), ('SCIM_SYNC_ERROR', 'Scim Sync Error'), ('ROLE_DEFINITION_CHANGED', 'Role Definition Changed'), ('PUSH_CONFIG_UPDATED', 'Push Config Updated'), ('PASSWORD_RESET_LINK_GENERATED', 'Password Reset Link Generated')], db_index=True, max_length=64),
        ),
    ]
