# Generated by Django 4.2.30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0186_audit_password_reset_link_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='identifier',
            field=models.TextField(db_index=True, verbose_name='Project Identifier'),
        ),
        migrations.AlterField(
            model_name='projectidentifier',
            name='name',
            field=models.TextField(db_index=True),
        ),
    ]
