# Generated by Django 4.2.30 on 2026-09-13 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0187_project_identifier_no_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='primary_teamspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_projects', to='db.teamspace'),
        ),
        migrations.AddField(
            model_name='teamspace',
            name='default_project_identifier',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workspace',
            name='default_project_identifier',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
