# Generated by Django 4.2.30 on 2026-09-13 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0188_project_primary_teamspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='sequence_teamspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pool_issues', to='db.teamspace'),
        ),
        migrations.AddField(
            model_name='issuesequence',
            name='teamspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teamspace_issue_sequences', to='db.teamspace'),
        ),
    ]
