# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Inspection compliance (ISO/IEC 17020 §4.1 impartiality / §4.2
confidentiality) - see `plane.db.models.inspection` for the design.

Schema only, NO data backfill, deliberately: every new `Project` field has a
default, no existing project is an inspection (`is_inspection_enabled`
defaults False, so this migration changes no observable behaviour), and
`InspectionObligation` rows are created lazily on the request path rather
than seeded - see that model's own docstring for why.

Generated by Django 4.2.30.
"""

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.mixins
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0191_restart_pool_numbering_at_one'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionDocumentTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('IMPARTIALITY', 'Impartiality declaration (§4.1)'), ('CONFIDENTIALITY', 'Confidentiality agreement / NDA (§4.2)'), ('ETHICS_CHARTER', 'Mission ethics charter')], max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Inspection Document Template',
                'verbose_name_plural': 'Inspection Document Templates',
                'db_table': 'inspection_document_templates',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InspectionDocumentTemplateVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('version', models.PositiveIntegerField()),
                ('body', models.TextField(blank=True, default='')),
                ('questionnaire_schema', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('requires_resignature', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_template_versions', to='db.fileasset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='db.inspectiondocumenttemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Inspection Document Template Version',
                'verbose_name_plural': 'Inspection Document Template Versions',
                'db_table': 'inspection_document_template_versions',
                'ordering': ('template', '-version'),
            },
            bases=(plane.db.mixins.ChangeTrackerMixin, models.Model),
        ),
        migrations.AddField(
            model_name='project',
            name='inspection_enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='inspection_enforcement_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='inspection_grace_period_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='project',
            name='inspection_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('SEMI_AUTOMATIC', 'Semi-automatic'), ('FULLY_AUTOMATIC', 'Fully automatic')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='inspection_review_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_projects_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='is_inspection_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InspectionObligation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('IMPARTIALITY', 'Impartiality declaration (§4.1)'), ('CONFIDENTIALITY', 'Confidentiality agreement / NDA (§4.2)'), ('ETHICS_CHARTER', 'Mission ethics charter')], max_length=32)),
                ('obligation_started_at', models.DateTimeField()),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_count', models.PositiveSmallIntegerField(default=0)),
                ('blocked_since', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_obligations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Inspection Obligation',
                'verbose_name_plural': 'Inspection Obligations',
                'db_table': 'inspection_obligations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='inspectiondocumenttemplate',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project'),
        ),
        migrations.AddField(
            model_name='inspectiondocumenttemplate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='inspectiondocumenttemplate',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace'),
        ),
        migrations.CreateModel(
            name='InspectionSignature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('kind', models.CharField(choices=[('IMPARTIALITY', 'Impartiality declaration (§4.1)'), ('CONFIDENTIALITY', 'Confidentiality agreement / NDA (§4.2)'), ('ETHICS_CHARTER', 'Mission ethics charter')], max_length=32)),
                ('signed_at', models.DateTimeField()),
                ('signature_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('signer_email_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('document_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('questionnaire_answers', models.JSONField(blank=True, default=dict)),
                ('declared_conflicts', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('NOT_REQUIRED', 'Review not required'), ('PENDING', 'Pending review'), ('ACCEPTED', 'Accepted'), ('ACCEPTED_WITH_MEASURES', 'Accepted with mitigation measures'), ('REJECTED', 'Rejected - evaluator excluded')], default='NOT_REQUIRED', max_length=32)),
                ('risk_level', models.CharField(blank=True, choices=[('NONE', 'No identified risk'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=16, null=True)),
                ('mitigation_measures', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_signatures', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_%(class)s', to='db.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_reviews_performed', to=settings.AUTH_USER_MODEL)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='db.inspectiondocumenttemplateversion')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_%(class)s', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Inspection Signature',
                'verbose_name_plural': 'Inspection Signatures',
                'db_table': 'inspection_signatures',
                'ordering': ('-signed_at',),
                'indexes': [models.Index(fields=['project', 'member', 'kind'], name='inspection__project_60e8df_idx'), models.Index(fields=['project', 'review_status'], name='inspection__project_6cdc6e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='inspectionsignature',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'member', 'template_version'), name='inspection_signature_unique_member_version_per_project'),
        ),
        migrations.AddIndex(
            model_name='inspectionobligation',
            index=models.Index(fields=['last_reminder_sent_at'], name='inspection__last_re_45f502_idx'),
        ),
        migrations.AddConstraint(
            model_name='inspectionobligation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'member', 'kind'), name='inspection_obligation_unique_member_kind_per_project'),
        ),
        migrations.AddConstraint(
            model_name='inspectiondocumenttemplateversion',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('template', 'version'), name='inspection_template_version_unique_number_per_template'),
        ),
        migrations.AddConstraint(
            model_name='inspectiondocumenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', True)), fields=('workspace', 'kind'), name='inspection_template_unique_workspace_default_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='inspectiondocumenttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('project__isnull', False)), fields=('workspace', 'project', 'kind'), name='inspection_template_unique_project_override_per_kind'),
        ),
    ]
