# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Server-side strings for inspection compliance, in the recipient's own
language (ISO/IEC 17020 §4.1/§4.2).

## Why a dict and not Django's gettext

Django's translation machinery expects `.po`/`.mo` catalogues compiled at build
time, and this project ships none - `LocaleMiddleware` is not installed and no
`locale/` directory exists. Introducing that whole apparatus for the ~30 strings
two emails and one PDF need would be a disproportionate change, and it would put
these strings somewhere no reader of the PDF builder would look. So: one table,
keyed by language, with an English fallback.

## Which language

`Profile.language` (default "en"), i.e. the recipient's own setting rather than
the request's. That matters because the two places these strings are used are
asynchronous: a reminder email is composed by a Celery task with no request at
all, and a PDF is rendered for whoever asks, which may be an admin downloading
somebody else's declaration - the DOCUMENT is that signer's, but the labels
around it should read in the language of the person looking at it.

## What is NOT translated, ever

The document body and the questionnaire's question wording. Those are the legal
text the evaluator accepted; an evidentiary record has to reproduce exactly what
was signed, and a translated clause is a different clause. See
`plane.db.models.inspection.DEFAULT_IMPARTIALITY_QUESTIONNAIRE`.
"""

FALLBACK_LANGUAGE = "en"

# Only the chrome: labels, headings and the evidence block's field names.
_STRINGS = {
    "en": {
        "kind.IMPARTIALITY": "Impartiality declaration (§4.1)",
        "kind.CONFIDENTIALITY": "Confidentiality agreement (NDA, §4.2)",
        "kind.ETHICS_CHARTER": "Mission ethics charter",
        "pdf.title": "Signed document",
        "pdf.evidence": "Signature evidence",
        "pdf.project": "Project",
        "pdf.document": "Document",
        "pdf.version": "Version",
        "pdf.signatory": "Signatory",
        "pdf.typed_name": "Name as typed",
        "pdf.email": "Email address",
        "pdf.signed_at": "Signed on",
        "pdf.ip": "IP address",
        "pdf.checksum": "Document checksum (SHA-256)",
        "pdf.answers": "Questionnaire answers",
        "pdf.question": "Question",
        "pdf.answer": "Answer",
        "pdf.review": "Managerial review (§4.1)",
        "pdf.review_status": "Verdict",
        "pdf.risk_level": "Impartiality risk",
        "pdf.measures": "Mitigation measures",
        "pdf.reviewed_by": "Reviewed by",
        "pdf.reviewed_at": "Reviewed on",
        "pdf.declared_conflicts": "Disclosure recorded",
        "pdf.footer": "Generated by Plane - evidentiary copy, retains the text as signed.",
        "pdf.not_translated": "The document text below is reproduced exactly as signed and is never translated.",
        "answer.yes": "Yes",
        "answer.no": "No",
        "answer.true": "True",
        "answer.false": "False",
        "review.NOT_REQUIRED": "Review not required",
        "review.PENDING": "Pending review",
        "review.ACCEPTED": "Accepted",
        "review.ACCEPTED_WITH_MEASURES": "Accepted with mitigation measures",
        "review.REJECTED": "Rejected",
        "risk.NONE": "No identified risk",
        "risk.LOW": "Low",
        "risk.MEDIUM": "Medium",
        "risk.HIGH": "High",
        "email.reminder_subject": "Action required: inspection documents to sign",
        "email.blocked_subject": "Access suspended: unsigned inspection documents",
    },
    "fr": {
        "kind.IMPARTIALITY": "Déclaration d'impartialité (§4.1)",
        "kind.CONFIDENTIALITY": "Engagement de confidentialité (NDA, §4.2)",
        "kind.ETHICS_CHARTER": "Charte d'éthique de la mission",
        "pdf.title": "Document signé",
        "pdf.evidence": "Preuve de signature",
        "pdf.project": "Projet",
        "pdf.document": "Document",
        "pdf.version": "Version",
        "pdf.signatory": "Signataire",
        "pdf.typed_name": "Nom saisi",
        "pdf.email": "Adresse email",
        "pdf.signed_at": "Signé le",
        "pdf.ip": "Adresse IP",
        "pdf.checksum": "Empreinte du document (SHA-256)",
        "pdf.answers": "Réponses au questionnaire",
        "pdf.question": "Question",
        "pdf.answer": "Réponse",
        "pdf.review": "Revue managériale (§4.1)",
        "pdf.review_status": "Verdict",
        "pdf.risk_level": "Risque pour l'impartialité",
        "pdf.measures": "Mesures de réduction du risque",
        "pdf.reviewed_by": "Revu par",
        "pdf.reviewed_at": "Revu le",
        "pdf.declared_conflicts": "Déclaration enregistrée",
        "pdf.footer": "Généré par Plane - copie probante, conserve le texte tel que signé.",
        "pdf.not_translated": (
            "Le texte du document ci-dessous est reproduit exactement tel que signé "
            "et n'est jamais traduit."
        ),
        "answer.yes": "Oui",
        "answer.no": "Non",
        "answer.true": "Vrai",
        "answer.false": "Faux",
        "review.NOT_REQUIRED": "Revue non requise",
        "review.PENDING": "En attente de revue",
        "review.ACCEPTED": "Accepté",
        "review.ACCEPTED_WITH_MEASURES": "Accepté avec mesures",
        "review.REJECTED": "Refusé",
        "risk.NONE": "Aucun risque identifié",
        "risk.LOW": "Faible",
        "risk.MEDIUM": "Moyen",
        "risk.HIGH": "Élevé",
        "email.reminder_subject": "Action requise : documents d'inspection à signer",
        "email.blocked_subject": "Accès suspendu : documents d'inspection non signés",
    },
}


def normalize_language(language) -> str:
    """Map a `Profile.language` value onto a key of `_STRINGS`.

    Tolerates regional tags (`pt-BR`, `zh-CN`) and casing, falling back to the
    base language and then to English - a profile holding something unexpected
    must never break a reminder email or a PDF download.
    """
    if not language or not isinstance(language, str):
        return FALLBACK_LANGUAGE
    candidate = language.strip()
    if candidate in _STRINGS:
        return candidate
    lowered = candidate.lower().replace("_", "-")
    for key in _STRINGS:
        if key.lower() == lowered:
            return key
    base = lowered.split("-")[0]
    for key in _STRINGS:
        if key.lower().split("-")[0] == base:
            return key
    return FALLBACK_LANGUAGE


def translate(key: str, language=None) -> str:
    """Look `key` up in `language`, falling back to English and then to the key
    itself - a missing string shows as its key rather than crashing a download."""
    resolved = normalize_language(language)
    table = _STRINGS.get(resolved, {})
    if key in table:
        return table[key]
    return _STRINGS[FALLBACK_LANGUAGE].get(key, key)


def supported_languages() -> tuple:
    return tuple(_STRINGS)
