# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

"""Category 11 (docs/feature-specs/11-admin-security-sso.md in
plane-selfhost), feature 1 "SSO SAML 2.0 natif" - instance-admin (god-mode)
serializers."""

from rest_framework import serializers

from plane.license.models import InstanceSAMLConfiguration, SAMLVerifiedDomain
from plane.utils.saml_xml import normalize_certificate_pem

from .base import BaseSerializer


class SAMLVerifiedDomainSerializer(BaseSerializer):
    class Meta:
        model = SAMLVerifiedDomain
        fields = "__all__"
        read_only_fields = [
            "id",
            "saml_configuration",
            "verification_token",
            "is_verified",
            "verified_at",
            "created_by",
            "updated_by",
            "created_at",
            "updated_at",
        ]

    def validate_domain(self, value):
        value = (value or "").strip().lower()
        if not value or "." not in value or " " in value:
            raise serializers.ValidationError("Enter a valid domain (e.g. example.com).")
        return value


class InstanceSAMLConfigurationSerializer(BaseSerializer):
    # Exigence 3 - lets a single GET on a configuration show its domains'
    # verification status without a separate list endpoint.
    domains = SAMLVerifiedDomainSerializer(many=True, read_only=True)

    class Meta:
        model = InstanceSAMLConfiguration
        fields = "__all__"
        read_only_fields = [
            "id",
            # Exigence 5 - generated by the view at creation time from
            # this instance's own public base URL + the row's own id,
            # never admin-entered.
            "sp_entity_id",
            "created_by",
            "updated_by",
            "created_at",
            "updated_at",
        ]

    def validate_attribute_mapping(self, value):
        if not isinstance(value, dict) or not (value.get("email") or "").strip():
            raise serializers.ValidationError("attribute_mapping must include a non-empty 'email' key.")
        return value

    def validate_idp_certificate(self, value):
        # `normalize_certificate_pem` tolerates a bare base64 body pasted
        # without PEM headers (some IdP metadata viewers only show that) -
        # match that same leniency here rather than being stricter at
        # input time than at actual verification time. Real cryptographic
        # validity (parseable, not expired, etc.) is only checked for
        # real at assertion-verification time - this is a cheap sanity
        # check so an obviously-empty/garbage paste is rejected
        # immediately with a clear message.
        try:
            from cryptography import x509

            x509.load_pem_x509_certificate(normalize_certificate_pem(value).encode())
        except Exception:
            raise serializers.ValidationError(
                "This does not look like a valid PEM-encoded X.509 certificate."
            )
        return value
