# Generated by Django 4.2.30 on 2026-08-23 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.license.models.saml
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0008_instance_max_session_timeout_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceSAMLConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('idp_entity_id', models.CharField(max_length=1000)),
                ('idp_sso_url', models.URLField(max_length=1000)),
                ('idp_slo_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('idp_certificate', models.TextField(help_text='PEM-encoded X.509 certificate the IdP signs assertions with.')),
                ('metadata_url', models.URLField(blank=True, help_text='Optional IdP metadata URL, stored for a future auto-refresh mechanism. Not auto-fetched today.', max_length=1000, null=True)),
                ('sp_entity_id', models.CharField(blank=True, max_length=1000)),
                ('attribute_mapping', models.JSONField(default=plane.license.models.saml.get_default_attribute_mapping)),
                ('signature_algorithm', models.CharField(choices=[('rsa-sha256', 'RSA-SHA256'), ('rsa-sha384', 'RSA-SHA384'), ('rsa-sha512', 'RSA-SHA512')], default='rsa-sha256', max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('enforce_sso', models.BooleanField(default=False)),
                ('clock_skew_tolerance_seconds', models.PositiveIntegerField(default=180)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Instance SAML Configuration',
                'verbose_name_plural': 'Instance SAML Configurations',
                'db_table': 'instance_saml_configurations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SAMLVerifiedDomain',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('verification_token', models.CharField(max_length=64)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('saml_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='license.instancesamlconfiguration')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'SAML Verified Domain',
                'verbose_name_plural': 'SAML Verified Domains',
                'db_table': 'saml_verified_domains',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SAMLAssertionReplay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('assertion_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('saml_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_assertions', to='license.instancesamlconfiguration')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'SAML Assertion Replay',
                'verbose_name_plural': 'SAML Assertion Replays',
                'db_table': 'saml_assertion_replays',
                'ordering': ('-created_at',),
            },
        ),
    ]
