# Generated by Django 4.2.30 on 2026-08-25 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import plane.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('license', '0010_enable_scim_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotificationConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('vapid_private_key', plane.db.fields.EncryptedTextField(blank=True, null=True)),
                ('vapid_admin_email', models.CharField(blank=True, max_length=255, null=True)),
                ('fcm_service_account_json', plane.db.fields.EncryptedTextField(blank=True, null=True)),
                ('apns_key_id', models.CharField(blank=True, max_length=255, null=True)),
                ('apns_team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('apns_auth_key', plane.db.fields.EncryptedTextField(blank=True, null=True)),
                ('apns_topic', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Push Notification Config',
                'verbose_name_plural': 'Push Notification Configs',
                'db_table': 'push_notification_configs',
                'ordering': ('-created_at',),
            },
        ),
    ]
