# Copyright (c) 2023-present Plane Software, Inc. and contributors
# SPDX-License-Identifier: AGPL-3.0-only
# See the LICENSE file for details.

# Module imports
from .base import BaseSerializer
from .user import UserLiteSerializer
from plane.db.models import ProjectUpdate


class ProjectUpdateWriteSerializer(BaseSerializer):
    """Writable via the existing manual create/edit endpoint
    (`ProjectUpdateViewSet`). The `ai_*` fields are writable here so that,
    per category 9 feature 6 (docs/feature-specs/09-ai-features.md "6.
    Redaction assistee des mises a jour de statut" in plane-selfhost), a
    human publishing a draft generated by
    `plane.utils.project_update_ai_draft.generate_project_update_draft`
    passes that response's `draft_content`/`ai_generation_status`/
    `ai_generation_metadata`/`ai_source_snapshot` straight through as part
    of the SAME publish request - creation/publication itself is completely
    unchanged and stays this exact endpoint (see that module's docstring:
    generation never creates a `ProjectUpdate` row itself).
    """

    class Meta:
        model = ProjectUpdate
        fields = [
            "id",
            "status",
            "description_html",
            "generated_summary_json",
            "is_summary_edited",
            "is_ai_assisted",
            "ai_draft_content",
            "ai_generation_status",
            "ai_generation_metadata",
            "ai_source_snapshot",
            "ai_regeneration_count",
        ]


class ProjectUpdateSerializer(BaseSerializer):
    created_by_detail = UserLiteSerializer(read_only=True, source="created_by")

    class Meta:
        model = ProjectUpdate
        fields = [
            "id",
            "workspace_id",
            "project_id",
            "status",
            "description_html",
            "generated_summary_json",
            "is_summary_edited",
            "is_ai_assisted",
            "ai_draft_content",
            "ai_generation_status",
            "ai_generation_metadata",
            "ai_source_snapshot",
            "ai_regeneration_count",
            "created_at",
            "updated_at",
            "created_by",
            "created_by_detail",
        ]
        read_only_fields = fields
